name: Touchstone Tests

on:
  push:
    branches:
      - 'develop'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        working-directory: ./src
        run: |
          pipenv install --dev
      - name: Install Touchstone
        working-directory: ./src
        run: |
          pipenv install -e .
      - name: Run Touchstone Tests
        working-directory: ./src/touchstone-tests/touchstone
        run: |
          pipenv run touchstone run
