name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        working-directory: ./src
        run: |
          pipenv install --dev
      - name: Test with pytest
        working-directory: ./src
        run: |
          pipenv install pytest
          pipenv run pytest
